name: Run Login Script
on:
  schedule:
    - cron: '43 1 * * *' # 北京时间9:43
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install requests library
      run: |
        pip install requests
    - name: Run Login Script
      env:
        ARG1: ${{ secrets.COOKIE }}
        ARG2: ${{ secrets.KEY }}
      run: |
        cd src
        python login.py $ARG1 $ARG2
