name: gptdos_login
on:
  schedule:
    - cron: "43 3 * * *"
jobs:
  build:
    runs-on: ubuntu-18.04
  steps:
    - name: checkout actions
    - uses: actions/checkout@v1
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: login
      run python src/login.py
